name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: Install deps
        run: bun install --frozen-lockfile
      - name: Typecheck
        run: bun run typecheck
      - name: Lint
        run: bun run lint
      - name: Unit tests
        run: bun run test
      - name: Build
        run: bun run build
      - name: Install Playwright Browsers
        run: bunx playwright install --with-deps
      - name: E2E tests
        run: bun run test:e2e
      - name: Upload preview artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist


